services:
  db:
    image: container-registry.oracle.com/database/free:latest
    container_name: db
    environment:
      - ORACLE_SID=FREE
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_PWD=Oracle_123
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/back
    expose:
      - "1521"
    restart: always

  tomee:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
      - "9010:9010"
    environment:
      - CATALINA_OPTS=-Dcom.sun.management.jmxremote 
          -Dcom.sun.management.jmxremote.port=9010 
          -Dcom.sun.management.jmxremote.rmi.port=9010 
          -Dcom.sun.management.jmxremote.local.only=false 
          -Dcom.sun.management.jmxremote.authenticate=false 
          -Dcom.sun.management.jmxremote.ssl=false 
          -Djava.rmi.server.hostname=127.0.0.1
      - DISPLAY=host.docker.internal:0 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  


volumes:
  oracle-data:
  oracle-backup: